apiVersion: 1

contactPoints:
  - orgId: 1
    name: telegram-alert
    receivers:
      - uid: telegram1
        type: telegram
        settings:
          bottoken: ${TELEGRAM_BOT_TOKEN}
          chatid: ${TELEGRAM_CHAT_ID}
          parse_mode: Markdown          
          message: |
            ğŸš¨ ALERT: {{ .CommonAnnotations.summary }}
            
            ğŸ”¥ Status: {{ .Status }}
            ğŸ“ˆ Value: {{ .Values }}
            ğŸ· Labels: {{ .CommonLabels }}
